### ISSUE TITLE
Pods-table column mismatch

### ISSUE THREAD

**Issue by randy-weinstein** [aws-samples/amazon-eks-inter-az-traffic-visibility#14]
The pods-table columns don't match the data when deployed on (EKS) K8s ver 1.25.
The column order is "name, ip, app, creation_time, node, labels" but "creation_time" has DNS name, "node" has the AZ, and "labels" has timestamp.
Here is a screenshot from Athena of a simple select *
![EKS cross-az traffic visibility-Pods-table-columns](https://github.com/aws-samples/amazon-eks-inter-az-traffic-visibility/assets/53484869/6c3afeff-d62b-441d-acda-944591cab783)

**Comment by fibert** [comment]
Thank you for bringing this up! I will take a look.

**Comment by fibert** [comment]
The issue got auto-closed, #15 should fix this issue.
Feel free to reopen if needed.
